services:
  php:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: laravel-php
    image: harbor.anrostech.com/anros/crm-php-fpm:latest
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: docker/nginx/.
    container_name: laravel-nginx
    image: harbor.anrostech.com/anros/crm-nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"  # map host port 8080 â†’ container port 80
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

